//
// Created by Truong on 05/04/2025.
//

#ifndef VEHICLE_ROUTING_PROBLEM_AS_QUBO_MARINE_INVENTORY_ROUTING_PROBLEM_H
#define VEHICLE_ROUTING_PROBLEM_AS_QUBO_MARINE_INVENTORY_ROUTING_PROBLEM_H


class MarineInventoryRoutingProblem {

};


#endif //VEHICLE_ROUTING_PROBLEM_AS_QUBO_MARINE_INVENTORY_ROUTING_PROBLEM_H
