//
// Created by Truong on 05/04/2025.
//

#ifndef VEHICLE_ROUTING_PROBLEM_AS_QUBO_ROUTING_PROBLEM_FACTORY_H
#define VEHICLE_ROUTING_PROBLEM_AS_QUBO_ROUTING_PROBLEM_FACTORY_H


class RoutingProblemFactory {

};


#endif //VEHICLE_ROUTING_PROBLEM_AS_QUBO_ROUTING_PROBLEM_FACTORY_H
